# test
name: Create a pull request if there is a difference
on:
  workflow_dispatch:
  schedule:
    # æ¯é€±æœˆæ›œæ—¥ã®9æ™‚ã«å®Ÿè¡Œ
    - cron: "0 9 * * 1"
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  copy-target:
    name: copy .github
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Checkout akidon0000/github-config repository
        uses: actions/checkout@v4
        with:
          repository: akidon0000/github-config
          path: repo-to-checkout

      - name: Sync .github directory
        run: |
          rsync -a repo-to-checkout/.github/ .github/

      - name: Check for changes
        id: git-diff
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .github
          git diff --cached --exit-code || echo "Changes detected"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update .github directory from akidon0000/github-config
          delete-branch: true
          title: "[ğŸ¤–] Update .github directory"
          reviewers: akidon0000
